module.exports = {
  TEST: '/test',
  RATE: '/rate',
  RATE_UPDATE: '/rate/update',
  GET_RATE_BY_USER: '/rate/get',
  ORDER: '/order',
  ORDER_ID: '/order/:orderId',
  ORDER_USER: '/order/:userId/:status/:isSeller',
  ORDER_STATUS: '/order/status',
  PRODUCTION: '/production',
  PRO_PID: '/production/pid/:productionID',
  PRO_USER: '/production/user/:userId',
  PRO_NAME: '/production/name/:name',
  PRO_UPDATE: '/production/update',
  MESSAGE: '/message',
  MESSAGE_LAST: '/message/last',
  MESSAGE_STATUS: '/message/status',
  USER: '/user',
  USER_ID: '/user/:userId',
  USER_EMAIL: '/user/:email/:password',
  USER_PROFILE: '/user/profile',
};
