# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: clean npm install
      run: rm -rf ./node_modules
    - name: install npm packages
      run: npm ci
    - run: if pm2 delete 'backend'; then               
             echo "stopped";             
           else               
             echo "set up";           
           fi
    - name: start pm2 service
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        NODE_PORT: ${{ secrets.TEST_PORT }}
      run: PORT=$NODE_PORT NODE_ENV=$NODE_ENV pm2 start ./bin/www --name 'backend'
